### ISSUE TITLE
Migrate github.com/Jermolene/TiddlyWiki5 to github.com/TiddlyWiki/TiddlyWiki

### ISSUE THREAD

**Issue by Jermolene** [TiddlyWiki/TiddlyWiki5#3114]
Tasks:

* [ ] Talk to someone who has made this transition before for a similar sized project
* [ ] Notify and consult GitHub of our intentions (@Jermolene)
* [ ] Appoint formal project roles, and document on tiddlywiki.com/dev, and processes for dealing with issues and PRs etc. (we shouldn’t write these ourselves)
* [ ] Flip the switch at GitHub (@Jermolene)
* [ ] Update documentation references/links

**Comment by twMat** [comment]
Reading this makes me happy! To get things rolling, what actions can we/you start to take?

> Talk to someone who has made this transition before for a similar sized project

Maybe ask on the boards? Or do you know of anyone in particular? (or does anyone else reading this know anyone?)

> Notify and consult GitHub of our intentions (@Jermolene)

...if you're going to consult them, just maybe they are able to advice regarding the first task? ...in which case maybe it is time for contacting them already now? Can someone else than you do this or do you want to do it personally?

> Appoint formal project roles, and document on tiddlywiki.com/dev, and processes for dealing with issues and PRs etc. (we shouldn’t write these ourselves)

This is something we can get started with right away. This is also beneficial because it would probably engage these individuals even more already now.

**Comment by Jermolene** [comment]
I've just realised that it might help to migrate https://github.com/Jermolene/TiddlyDesktop to the TiddlyWiki organization first before we attempt the TW5 repo.

**Comment by ento** [comment]
@Jermolene [wrote in another issue](https://github.com/Jermolene/TiddlyWiki5/issues/3834#issuecomment-666975558):

> There is actually another issue: whether we should move TiddlyWiki5 into the TiddlyWiki organisation, or create a new TiddlyWiki5 organisation. I'm thinking primarily of convenience for visitors who might be confused by material for the two versions being intermixed, but it would also likely simplify setting up permissions. 

If we use a single organization, in what context would material for the two versions be intermixed?

I can see the repository names could be confusing

- TiddlyWiki/TiddlyWiki5
- TiddlyWiki/TiddlyWiki ("Is this the latest and greatest TiddlyWiki? Oh, it's classic?")

Maybe the latter can be named TiddlyWiki/TiddlyWiki-classic.

One thing in favor of using a single organization is that it can be easier to find the repo you were looking for when you ended up in the wrong place: the organization name visible at the top provides a navigation path to all the repos related to TiddlyWiki, in addition to any pointers the repo might provide.

> Then we've got TiddlyDesktop which applies to both TW Classic and TW5. It seems overboard to create a TiddlyDesktop organization but it would give us a natural way to create an independent website for it.

Hmm, natural as in..? Like being able to host a [GitHub Pages site](https://docs.github.com/en/github/working-with-github-pages/about-github-pages#types-of-github-pages-sites) at `https://TiddlyDesktop.github.io/`? Or being able to have a repo at something like TiddlyDesktop/website?

**Comment by Jermolene** [comment]
Hi @ento 

> If we use a single organization, in what context would material for the two versions be intermixed?

I should have been clearer, I primarily meant the list of repositories at https://github.com/TiddlyWiki would intermix Classic and 5. Using a single repo will also mean sharing a security context (as I understand it, the scope of teams etc are organisations).

> Maybe the latter can be named TiddlyWiki/TiddlyWiki-classic.

I'd wondered about that. (Perhaps "TiddlyWikiClassic" for consistency)

> One thing in favor of using a single organization is that it can be easier to find the repo you were looking for when you ended up in the wrong place: the organization name visible at the top provides a navigation path to all the repos related to TiddlyWiki, in addition to any pointers the repo might provide.

Yes, there's something in that.

> Hmm, natural as in..? Like being able to host a GitHub Pages site at https://TiddlyDesktop.github.io/? Or being able to have a repo at something like TiddlyDesktop/website?

Yes, sorry, I was indeed thinking of ease of setting up GitHub Pages site.

**Comment by ento** [comment]
> I primarily meant the list of repositories at https://github.com/TiddlyWiki would intermix Classic and 5. Using a single repo will also mean sharing a security context (as I understand it, the scope of teams etc are organisations).

Ah, I see. It's possible to configure all members of an organization [to have the same permission](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/setting-base-permissions-for-an-organization#setting-base-permissions) or set up teams within the organization and [give different permissions for different repositories](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-team-access-to-an-organization-repository) to each team.

> I was indeed thinking of ease of setting up GitHub Pages site.

The difference between the different org setups would be...

| URL | Organization | Pages source repo |
|-|-|-|
| https://TiddlyDesktop.github.io | TiddlyDesktop | TiddlyDesktop/TiddlyDesktop.github.io |
| https://TiddlyWiki.github.io/TiddlyDesktop | TiddlyWiki | TiddlyWiki/TiddlyDesktop |

As a user, my experience with accessing the site won't be much different between the two URLs. (I assume I'll land there from a search result or an existing link to the site.) It should also be possible to set up a custom domain name in either case.

If I were to set the site up...the ease of setup doesn't seem much different. (I've done both user-level pages site and project-level pages site before, but little to no experience with custom domain names.) So for what it's worth, the utility of having things under a single organization still seems a winner to me.

**Comment by Jermolene** [comment]
Hi @ento the TiddlyWiki repo currently uses a tiddlywiki.github.io repo, rather than the `gh-pages` branch, which means that the URL for TWC is `https://classic.tiddlywiki.com/index.html`, and not `https://classic.tiddlywiki.com/tiddlywiki/index.html`. I don't think we could switch to multiple `gh-pages` subsites without breaking that existing URL.

**Comment by ento** [comment]
So, if I'm understanding correctly, the ideal state requires the ability to host all project websites at the root of a subdomain (`classic.tiddlywiki.com`) or an apex domain (`tiddlywiki.com`).

I tried setting up some pages websites using a domain name I had lying around and that setup seems possible with a single organization/user:

Apex domain website based on a `<user>.github.io` repo

* Custom URL: https://pearlwaffles.xyz/
* Pages source: https://github.com/ento/ento.github.io

Subdomain website based on a project repo

* Custom URL: https://gemini.pearlwaffles.xyz/
* Pages source: https://github.com/ento/tw5-gemini-plugin/tree/gh-pages

---

Noting down my understanding of the ideal state (corrections welcome):

### TiddlyWiki5

* Custom URL: `https://tiddlywiki.com/index.html`
* Repo for Pages: `TiddlyWiki/tiddlywiki.github.com`
* Repo for application code: `TiddlyWiki/TiddlyWiki5`

### TiddlyWiki (classic)

* Custom URL: `https://classic.tiddlywiki.com/index.html`
* Repo for Pages: `TiddlyWiki/TiddlyWiki` (branch:`gh-pages`)
* Repo for application code: same as Pages repo

### TiddlyDesktop

* Custom URL: `https://tiddlydesktop.tiddlywiki.com/index.html`
* Repo for Pages: `TiddlyWiki/TiddlyDesktop` (branch: `gh-pages`)
* Repo for application code: same as Pages repo

**Comment by Jermolene** [comment]
> Subdomain website based on a project repo
> Custom URL: https://gemini.pearlwaffles.xyz/
> Pages source: https://github.com/ento/tw5-gemini-plugin/tree/gh-pages

Interesting. How is that accomplished? Via a CNAME file in the root of the gh-pages branch?

**Comment by pmario** [comment]
>Pages source: https://github.com/ento/tw5-gemini-plugin/tree/gh-pages

@ento ... Did you test this with the /docs directory. IMO using /docs as the gh-pages directory is much simpler as using a different branch. ... IMO switching branches to write to gh-pages and using master for the code is really confusing, even for devs.

**Comment by joshuafontany** [comment]
It is, but I use the git "worktree" settings to have both branches on disk in separate directories. Mostly for my plug-in repositories, as the demo wiki repo structure is a wiki folder while the plugin repo is a node plug in folder-structure.

**Comment by ento** [comment]
> > Subdomain website based on a project repo
> > Custom URL: https://gemini.pearlwaffles.xyz/
> > Pages source: https://github.com/ento/tw5-gemini-plugin/tree/gh-pages
> 
> Interesting. How is that accomplished? Via a CNAME file in the root of the gh-pages branch?

@Jermolene Yes, [the CNAME file](https://github.com/ento/tw5-gemini-plugin/blob/gh-pages/CNAME) plus an actual CNAME record for the `gemini` subdomain pointing at `ento.github.io`. I found [the official help documentation](https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site) to be a comprehensive how-to.

> > Pages source: https://github.com/ento/tw5-gemini-plugin/tree/gh-pages
> 
> @ento ... Did you test this with the /docs directory. 

Tested [with a new repo](https://github.com/ento/pages-test/tree/master/docs)--looks good: https://subdir-pages.pearlwaffles.xyz/

For the TW classic website, it can be kept as a separate repo while the migration to the organization account is happening, postponing the decision on whether to merge it with the main repo for classic and which branch / directory to use.

I perceive the migration to be a key change that unlocks the community's ability to take on various development activities (including issue management and such), and so I'm curious what the leanest path forward would be. From what's been discussed so far...:

- Move `TiddlyWiki/TiddlyDesktop` to the organization account as a trial. See if anything breaks
- Rename `TiddlyWiki/TiddlyWiki` to `TiddlyWikiClassic`?
- Rename `TiddlyWiki/tiddlywiki.github.com` to `classic.tiddlywiki.com`?
- Move `TiddlyWiki5` to the organization account
- Move `jermolene.github.io` to the organization account as `tiddlywiki.github.io` or `tiddlywiki.com` and update `bin/travis-push.sh` to push to the new repo


Once the migration is over...

- Re-organize how Pages websites are managed? (branch vs separate repo, which branch, etc)
   - If the publishing process for a site is all automated (thinking of TiddlyWiki5), having a separate repo (where people could open PRs mistakenly) may not have a lot of benefits.
- Set up tiddlydesktop.tiddlywiki.com?

**Comment by pmario** [comment]
The problem with the [existing structure](https://github.com/Jermolene/TiddlyWiki5) is, that it's a mono-repo. We can't have different roles. .. 

As far as I know, with github it isn't possible to have "merge rights" for different users to different sub-directories. It's only possible to define rights per repo. ...

So IMO just moving the existing structure to a new organization won't improve anything in terms of faster release cycle. 

We do have a `tiddlywiki-com` branch, which allows changes to `/editions/tw5.com` but working with branches, which are published separately, is confusing and not really efficient. ... Is it possible to assign "merge rights" to branches?

**Comment by ento** [comment]
> Is it possible to assign "merge rights" to branches?

I don't think so, unless we implement something custom with GitHub Actions / Travis + [required status checks](https://docs.github.com/en/github/administering-a-repository/enabling-required-status-checks). (I can only think of something approximate though: require reviews from different group(s) of people based on the details of the PR, and then anyone with write access can merge.)

> So IMO just moving the existing structure to a new organization won't improve anything in terms of faster release cycle.

I'm in agreement there - though I see these structural changes as something that can be done independently to the move to a new organization. I don't mean to say that your intention in bringing this up was to assert that the two need to be done together, but I do worry that discussing other changes in this issue may make it appear as if they block the migration. (Happy to be corrected if structural changes are actually a prerequisite to the migration.)

Faster release cycle can mean a few things: faster turnaround time for bringing resolution to issues, shorter time between releases, shorter time-to-merge for PRs, etc. I believe the migration to a new org is a stepping stone toward addressing at least a part of these. A better home for a discussion of what lies beyond may be  #3834, or a new umbrella issue that encompasses #3313 (and/or anything else that mentions issue management) and faster release cycle for tw5.com in addition (a quick search didn't turn up an issue that's about tw5.com specifically).

**Comment by pmario** [comment]
@ento 

>(I can only think of something approximate though: require reviews from different group(s) of people based on the details of the PR, and then anyone with write access can merge.)

Ahh. So it may be possible to "enable merging" only if the review process is "resolved". Eg: may be 3 out of 5 (for docs) and 4 out of 5 (for code) say it's ok. ... That may be enough.

**Comment by pmario** [comment]
> Faster release cycle can mean a few things: ....

You are right. That's 2 different things. ... But 1 think what we urgently need is faster documentation update and easier access for the community to the documentation editions ... all of them. ... 

eg: every edition, that starts with a language code `at-, de-, es-, fr-, ja-, ko-, zh-` could probably move much faster, if they would be separated. ... I think the barrier for contributors would also be much lower, since contributing to documentation can't break the functionality. ... So the rules for merging can be much more relaxed. 

`tw5.com` and `tw5.com-docs` are also documentation only, BUT merging rules need to be more strict, since this documentation has some core-version dependency. 

just some thoughts.

**Comment by Jermolene** [comment]
I am still keen to proceed with this move, and propose (all being well) to carry it out around the 24th July 2024.

**Comment by Jermolene** [comment]
Happy to report that the migration was successfully completed today.

**Comment by twMat** [comment]
>Happy to report that the migration was successfully completed today.

Wonderful! Well done. To my relief I note that this means bookmarks etc are automatically *redirected* !

**Comment by Jermolene** [comment]
We've found one unexpected consequence: our Vercel previews no longer work and cannot be restored without payment to Vercel. See #8420
