### ISSUE TITLE
Feature: Loading indicator when tiddler is loading by loadTiddler()

### ISSUE THREAD

**Issue by linonetwo** [TiddlyWiki/TiddlyWiki5#4420]
When loading, tiddler's content will be blank, and without any indicator.

Is there a way to detect tiddler is being loading by SyncAdaptor, so I can add a loading indicator to it?

**Comment by Jermolene** [comment]
Hi @linonetwo there's no support for that at present, but there's nothing stopping a syncadaptor from adding a view template segment with a loading indicator driven by its own data.

**Comment by linonetwo** [comment]
What does `view template segment` mean?

Is there an API to update the title bar of a tiddler template programmatically? I think this is a little complex.

Seems there is a new syncer, will it handle tiddler level loading indicator?

**Comment by linonetwo** [comment]
I think we can check `_is_skinny` and use a cascade for this.

**Comment by linonetwo** [comment]
Done in https://github.com/tiddly-gittly/itonnote-plugin/commit/fe10d9bff6e2cf920d9a381b6359b9bf3819ded3 in [itonnote-plugin](https://github.com/tiddly-gittly/itonnote-plugin), build-in in TidGi app.

**Comment by Jermolene** [comment]
Hi @linonetwo that implementation looks good – albeit I don't recommend using embedded stylesheets in that way.

I'd be happy to see this functionality in the core. I would handle the animation slightly differently, using a similar technique that the tiddlywebadaptor uses for animating the cloud icon.
