### ISSUE TITLE
[BUG] Newly created tiddlers sort at the bottom of tag lists, by time created

### ISSUE THREAD

**Issue by sobjornstad** [TiddlyWiki/TiddlyWiki5#6382]
**Describe the bug**: If no list information is available for a tiddler, that tiddler is listed in order of *creation* in tag pills (after all alphabetically sorted items) until the wiki is reloaded. [This isn't supposed to happen.](https://talk.tiddlywiki.org/t/are-tiddlers-supposed-to-sort-in-order-created-during-the-current-session/1989)

**To Reproduce**
1. Grab a copy of `empty.html` (or start in an existing wiki).
2. Create a tiddler `B` with tag `T`.
3. Create a tiddler `A` with tag `T`.
4. Click the tag pill for `T`.

**Expected behavior**: The tiddlers are listed in the order `A B`, since A comes alphabetically before B and there is no `list`, `list-before`, or `list-after` information field on any of the tiddlers.

**Actual behavior**: The tiddlers are listed in the order `B A`, by the order of their creation.

After saving and reloading the wiki, they're correctly listed in the order `A B`. If list information is provided (e.g., by setting `list-after` on tiddler A to `B`), then they're displayed in the correct order. Removing the list information without reloading the wiki restores the incorrect order.

The problem occurs regardless of whether the tag tiddler `T` exists.

**TiddlyWiki Configuration (please complete the following information):**
 - Version: v5.2.1
 - Saving mechanism: Tested on Node.js and the download saver.
 - Plugins installed: None required to exhibit the behavior (except core, obviously)
 
**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Tested Chromium and Vivaldi
 - Version: All recent versions (currently on Chromium 96)

**Comment by Jermolene** [comment]
Thanks @sobjornstad I've created a draft PR with a failing test which I *think* corresponds to the issue – see #6383

**Comment by sobjornstad** [comment]
Looks right to me.

**Comment by pmario** [comment]
@sobjornstad -- Is the OP resolved? If yes please close.

There have been commits that should fix the problem.

**Comment by pmario** [comment]
@Jermolene -- IMO it seems this bug is fixed already - please close

**Comment by Jermolene** [comment]
Thanks @pmario @sobjornstad
