### ISSUE TITLE
[BUG] The tiddler editor font size seems to be set to body.tc-body instead of .tc-tiddler-frame .tc-tiddler-body

### ISSUE THREAD

**Issue by pmario** [TiddlyWiki/TiddlyWiki5#6506]
At the moment “Font size” and “Line height” are responsible for the global font setting, which is set to body.tc-body: 14px from the control panel. This setting is responsible for the elements outside the tiddler frame.

The “Font size for tiddler body” and “Line height for tiddler body” are used only for the tiddler body “ViewTemplate”.

It seems the editor uses body.tc-body settings, which can’t be changed from the TW UI atm. … IMO this is a bug. 

IMO the editor should have its own settings

**Comment by kookma** [comment]
Reference

*https://talk.tiddlywiki.org/t/changing-editor-font-size/2596
*https://talk.tiddlywiki.org/t/css-rule-for-the-font-in-the-edit-area/4581

Changing the font from  $:/ControlPanel > Appearance > ThemeTweaks (see Settings, Editor font family input) no only change the font of tiddler editor body but also the tiddler title input which is not desired.

**Comment by pmario** [comment]
IMO not a bug. Can be set by: $:/themes/tiddlywiki/vanilla/metrics/bodyfontsize -- so close this one
