### ISSUE TITLE
[BUG] Page Layout switch menu is not convenient

### ISSUE THREAD

**Issue by linonetwo** [TiddlyWiki/TiddlyWiki5#7067]
### Describe the bug

1. After using keyboard shortcut `ctrl+shift+L`, we can't use arror key to select a layout and use enter to confirm now. This asks the user to use both the keyboard and mouse.
2. When menu is opened, can't close it (and confirm selected layout) by click outside
3. When the menu is opened, we can still open more menus, then the user must click OK multiple times to close it.
4. not working in FireFox

https://user-images.githubusercontent.com/3746270/204124863-72547f57-83fc-409c-8578-a712d1a10e87.mov

### Expected behavior

1. Allow open that menu using mouse, from a page control button. Or allow using arror key and enter key in that menu
2. Disable shortcut when menu is opened
3. Allow click on mask to close the menu
4. should allow switch in Firefox, not only Chrome.

### To Reproduce

1. Go to https://tiddlywiki.com/ or https://tiddly-gittly.github.io/tiddlywiki-whiteboard/
2. using keyboard shortcut `ctrl+shift+L`  x5
3. Try arrow key and click on dark mask
5. See error

### Screenshots

See my screen recording above.

### TiddlyWiki Configuration

Official website, 5.2.3

### Additional context

I'm creating a whiteboard layout.

**Comment by Jermolene** [comment]
Thanks @linonetwo those would all be useful enhancements for the layout switcher.

**Comment by pmario** [comment]
I think the keyboard handling would needed to be implemented in wikitext in the switcher template. 

Closing the modal by clicking on the mask is a new function, which imo will need some changes to the modal.js code.

**Comment by linonetwo** [comment]
I don't know how to do keyboard handling using widget or macro, there seem to be a kbi widget, but is only for text input, not for list.

**Comment by pmario** [comment]
>  4. not working in FireFox

I'm using FF all the time. The function worked there all the time. So I don't understand this issue

**Comment by linonetwo** [comment]
oh, sorry it does worked...In [https://tiddly-gittly.github.io/tiddlywiki-calendar/](https://tiddly-gittly.github.io/tiddlywiki-calendar/) it is working.

But in [https://tiddly-gittly.github.io/tiddlywiki-whiteboard/](https://tiddly-gittly.github.io/tiddlywiki-whiteboard/) I can't switch in firefox, maybe it is a bug of my plugin.

**Comment by linonetwo** [comment]
> Closing the modal by clicking on the mask

This has been implemented.

> use arror key to select a layout

Difficult to implement using KBD in core wikitext, but already implemented in command palette plugin, and is supported in major community plugins.
