### ISSUE TITLE
[BUG] Unwrapped overflowed codeblocks not showing scroll bars

### ISSUE THREAD

**Issue by Leilei332** [TiddlyWiki/TiddlyWiki5#8278]
### Describe the bug

Setting "Wrap long lines in code blocks" to "No" in "Theme tweaks" cause the code to overflow.

![图片](https://github.com/Jermolene/TiddlyWiki5/assets/70204468/fa512744-260c-4361-9066-a4d49487ee39)

While the code blocks rendered by highlight.js shows a scroll bar under the code blocks.

### Expected behavior

A scroll bar should be shown under the overflowed code block.

The style `overflow-x: auto` should be applied to the element.

### TiddlyWiki Configuration

Tiddlywiki 5.2.4 prerelease

**Comment by pmario** [comment]
Your example does not show the `plain text` that creates the output.

**Comment by pmario** [comment]
The HTML CODE element does not respect any `overflow` settings. overflow requires a "block" element. CODE is an inline element. So the only way to "wrap lines" with extra long inline-code is to use `white-space: pre-wrap;` which is exactly, what the Theme-Tweak setting does. 

If you use **code-blocks** instead of `` `inline code` ``

    ```
    your-code-block-comes-here
    ```

It should work as expected.

**Comment by pmario** [comment]
I was wrong. If you remove `white-space: pre-wrap` from the CODE CSS and set `overflow: auto` it does scroll, but that would be a custom Stylesheet setting, since I do not know what the "side" effects are.

**Comment by pmario** [comment]
You could do this, if you want to force it into 1 line.

```
<pre style="overflow:auto">`sssssssssssssssssssssssssssssssssss sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
`</pre>
```

**Comment by Leilei332** [comment]
Actually, I did use code blocks in the screenshot.

Since you mentioned inline code, I tested them in tiddlywiki 5.3.4 prerelease with only highlight.js plugin installed.

![图片](https://github.com/Jermolene/TiddlyWiki5/assets/70204468/f5f0d7aa-4f3b-42b2-9106-ad9f72e2f727)

The plain text:

![图片](https://github.com/Jermolene/TiddlyWiki5/assets/70204468/5fb1c421-5b30-433f-adb3-a3626b4faf4b)

The inline code is unwrapped and overflowed. I think it shouldn't be unwrapped since it isn't a code block.

For the two code blocks, only the third code block which is rendered by highlight.js showed a scroll bar. The second one is overflowed.

**Comment by pmario** [comment]
You are right. It seems we do it wrong an highlight.js does it right. A bit more experimenting is needed. 

It seems hljs does set the class of the CODE element to `display: block; overflow-x: auto`, which seems to do the trick.
A bit of **padding** adjustment should be needed too. 

Nice catch  -- **Thanks for reporting**

**Comment by pmario** [comment]
![grafik](https://github.com/Jermolene/TiddlyWiki5/assets/374655/bd76b1c6-71c7-46ab-8c31-fff2b6c3afd3)
