### ISSUE TITLE
All toc macros should accept current tiddler as default tag parameter

### ISSUE THREAD

**Issue by springerspandrel** [TiddlyWiki/TiddlyWiki5#8289]
**Is your feature request related to a problem? Please describe.**
As noted in [this discussion](https://talk.tiddlywiki.org/t/table-of-contents-based-on-tiddler-name/10005/3?u=springer), It would be more consistent with other macros, such as tag macro, if toc macros (the whole family of them) defaulted to showing toc for the current tiddler whenever no parameter is specified. This kind of "toc-starting-here" is convenient in projects where the "home" node for each tags serves as an important (view-template enhanced) hub for information related to that tag. An intuitive view template for this purpose should not need anything more than `<<toc>>` (or `<<toc-selective-expandable>>`, etc.) to make a table of contents based on the current location as a tag home.

**Describe the solution you'd like**
This whole family of macros (`<<toc>> <<toc-expandable>> <<toc-selective-expandable>> <<toc-tabbed-internal-nav>> <<toc-tabbed-external-nav>>`) should all treat the current tiddler as the default tag value, if no parameter is specified.

**Describe alternatives you've considered**
Constructing a macro call with filter language to specify current tiddler as the tag parameter, so that a view template could add a toc within any tiddler which has tag-children. (It's not intuitive, and I wouldn't want to explain it to a beginner! But this should be a beginner-friendly feature to add.)

**Comment by Jermolene** [comment]
Thanks @springerspandrel that seems reasonable, it is probably one for @pmario

**Comment by pmario** [comment]
I'll have a closer look
