### ISSUE TITLE
Planning v5.3.5 bug fix release

### ISSUE THREAD

**Issue by Jermolene** [TiddlyWiki/TiddlyWiki5#8331]
A serious regression in v5.3.4 has come to light and so I plan to release v5.3.5 as a bug fix release around this weekend.

The fixes that will be included:

* #8327
* #8322
* #8332 
* #8317
* #8333 
* 6554b5c9f4f6888f0c25c833b775c3a74ea15531 - a reapplication of #8246 which had accidentally been reverted

I am happy to consider other PRs, but this is strictly limited to fixing bugs or regressions introduced in v5.3.4.

**Comment by Jermolene** [comment]
I also plan to investigate a fix for @btheado's report in #8330

**Comment by twMat** [comment]
If not implicit in the above already, please include fix for

[[BUG] not-added tags are not saved when saving tiddler #8328](https://github.com/Jermolene/TiddlyWiki5/issues/8328)

**Comment by twMat** [comment]
Please also include #8351 as it belongs to the general modification of the tag-picker macro.

**Comment by Jermolene** [comment]
v5.3.5 was released in a2426b5ed9d12f646dae403c7c1fdb0c5ccc4a23
