### ISSUE TITLE
[IDEA] Show message when tagpicker dropdown is empty

### ISSUE THREAD

**Issue by twMat** [TiddlyWiki/TiddlyWiki5#8343]
The dropdown is not good, arguably even confusing, when showing up empty like so:

<img width="305" alt="image" src="https://github.com/Jermolene/TiddlyWiki5/assets/4534056/0fcde439-5c35-4571-9b8b-4adb35340b70">

I propose to show some message like `(no search result)` or `(no tag exits containing that string)` or `(empty)` or some such.

**Comment by Leilei332** [comment]
This can be implemented by simply adding the `emptyMessage` attribute to the list widget.

![图片](https://github.com/Jermolene/TiddlyWiki5/assets/70204468/61bc6350-96e1-4e06-afff-16afe237fe6c)

![图片](https://github.com/Jermolene/TiddlyWiki5/assets/70204468/2b714d3a-95d1-4c30-a344-f7b253a8bf39)

**Comment by pmario** [comment]
If we do this for 1 search dropdown, IMO we need to do it for all of them -- for consistency. 

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/83124bb4-de9b-4058-93b4-8cdfe8acc92e)

**Advanced Search** will need "special" treatment.

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/c916d908-67ed-4246-9a09-f2185cee360b)

For **System** and **Shadows**-search we will probably need some special handling. Either show the one or the other

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/29e9024f-da4c-4113-874f-6f8e1106d409)

For **Filter**-search - there is a possibility to have 1 match, but an empty list. -- Any additional text there will cause confusion -- So we should not change that one.

**Comment by Jermolene** [comment]
Thanks I agree that this would be worth fixing, and making consistent if possible.
