### ISSUE TITLE
[IDEA] Display language plugins' info page properly

### ISSUE THREAD

**Issue by Leilei332** [TiddlyWiki/TiddlyWiki5#8345]
**Is your feature request related to a problem? Please describe.**
Yes. When I opened language plugins from the control panel, the raw json was displayed rather than an info page showing its contents. This may cause the whole page to crash (when the json is very large).

**Describe the solution you'd like**
An info page showing the contents of the language plugin (like the normal plugins and themes).

**Describe alternatives you've considered**
An info page showing some sample text, like "删除" for `zh-CN` and `zh-Hans`, "Delete" for `en-US` while "supprimer" for `fr-FR`.

**Comment by pmario** [comment]
For me it looks like this. It does show the content. So may be one of your theme or plugin did change something

![image](https://github.com/Jermolene/TiddlyWiki5/assets/374655/a4f59750-2183-44aa-8de1-023ba2608c98)

**Comment by Jermolene** [comment]
Thank you @Leilei332 I can confirm the issue

@pmario - you need to click the language plugin within control panel to load it as a separate tiddler:

<img width="1600" alt="image" src="https://github.com/Jermolene/TiddlyWiki5/assets/174761/6e5af617-3b83-4114-beab-7164faa8876b">
