### ISSUE TITLE
[BUG] Nested json does not produce separate fields with the http api and MWS server

### ISSUE THREAD

**Issue by andjar** [TiddlyWiki/TiddlyWiki5#8370]
### Describe the bug

Using the PUT method for the http api, it seems that the MWS server struggles with nested json for fields. With the ordinary server, the following json produces a tiddler with three fields: `a`, `c`, `e`. The MWS server, however, seems to create two fields; `a` and `fields` where `fields` contains the full json `{c": "d", e": "f"}`

```
{
	"title": "HelloThere",
	"tags": "FirstTag [[Second Tag]]",
        "a": "b",
	"fields": {
		"c": "d",
                "e": "f"		
	}
}
```

### TiddlyWiki Configuration

- Version 5.3.3, MWS edition from github
- Saving mechanism Node.js

**Comment by pmario** [comment]
@Jermolene -- I think the decision has been made.

Due to your last comment I think this issue can be closed with "wontfix" label.

**Comment by Jermolene** [comment]
Thanks @pmario – @andjar will this decision cause issues for you?

**Comment by andjar** [comment]
Thanks for following up @Jermolene - no problems, I think the main issue was that the inconsistency wasn't documented anywhere
