### ISSUE TITLE
[IDEA] Support image drag & drop (cut & paste) for markdown tiddlers

### ISSUE THREAD

**Issue by Leilei332** [TiddlyWiki/TiddlyWiki5#8388]
**Is your feature request related to a problem? Please describe.**
Yes. The editor didn't support dragging & dropping (cutting & pasting) images when the type field is `text/markdown`. Adding `[all[current]type[text/markdown]]` to `$:/config/Editor/EnableImportFilter` didn't work too. 

(I found that the message did appear for markdown tiddlers after modifying `$:/config/Editor/EnableImportFilter`, but the import dialog didn't appear. The import dialog only appears when the content type is `text/vnd.tiddlywiki` or empty.)

![图片](https://github.com/user-attachments/assets/c883ed97-c50a-446c-844d-e670f3d1f623)

**Describe the solution you'd like*
Markdown tiddlers support dragging and dropping (cutting and pasting) images like tiddlywiki tiddlers.

**Comment by saqimtiaz** [comment]
@Leilei332 see the following thread for how to enable this in markdown tiddlers: https://github.com/Jermolene/TiddlyWiki5/issues/7924#issuecomment-1882654241
