### ISSUE TITLE
Vercel Preview doesn't work after migration to TiddlyWiki/TiddlyWiki5

### ISSUE THREAD

**Issue by Jermolene** [TiddlyWiki/TiddlyWiki5#8420]
As reported by @pmario, the Vercel previews for TiddlyWiki PRs are no longer being updated.

I tried to re-enable them but received this error message:

![image](https://github.com/user-attachments/assets/efe3aa1e-dc49-419c-a8f8-adace81ebe45)

I had been using Vercel's free "hobby" tier, but it turns out to be quite tightly restricted, and does not appear to support open source projects residing in a shared organisation. The payments to continue using Vercel seem a considerable jump from the $0 we've been paying so far:

<img width="1122" alt="image" src="https://github.com/user-attachments/assets/4dc496fd-9225-4875-9ed2-ea7e3225f21c">

So, it appears that the two available choices are:

1. Pay the $20 per user per month fees
2. Find another provider who can produce the previews for organisation-based GitHub projects

I'd welcome relevant thoughts and suggestions.

**Comment by pmario** [comment]
It seems they have an "Open Source Plan". So since the whole TiddlyWiki organisation only contains Open Source stuff, there should be a possibility that they sponsor the TW project. IMO you should contact them for a sponsorship. "Asking is free" ;)

See: https://vercel.com/pricing and scroll down to the end. 

![grafik](https://github.com/user-attachments/assets/c5dee342-a09b-47a7-b386-299edc2a0489)

**Comment by Jermolene** [comment]
Hi @pmario it seems to be a closed program:

https://vercel.com/guides/can-vercel-sponsor-my-open-source-project

> Can Vercel sponsor my open source project?
> Yes. However, we are currently revamping the program.
> While some sponsorships have expired, our sponsorships program is still active. We will be accepting sponsorships again, soon. Individuals can still get started building on Vercel completely free. See the [free tier usage guidelines](https://vercel.com/docs/limits/fair-use-guidelines#typical-monthly-usage-guidelines) to learn more.
> We’re proud to have supported over 700 teams and individuals so far with almost $2M dollars of Vercel credits. This includes popular open-source projects like Tailwind CSS, Nuxt, Svelte, styled-components, as well as non-profits like the Red Cross.

**Comment by Jermolene** [comment]
Vercel's competitor Netlify offers an open source program, but they have non-trivial reciprocity requirements:

https://www.netlify.com/legal/open-source-policy/

> To qualify for the Open Source plan, a project must adhere to the following criteria:

> Includes a license listed on the [Open Source Initiative approved license list](https://opensource.org/licenses) or a [Creative Commons license](https://creativecommons.org/choose/) that includes “attribution” or places the work in the [public domain](https://creativecommons.org/publicdomain/).

> Features a [Code of Conduct](https://projectinclude.org/writing_cocs) at the top level directory of the project repository or prominently in the documentation (with a link in the navigation, footer, or homepage).

> Must feature a link to our service on your main page, or all internal pages. You have two options:

> We have [premade badges](https://www.netlify.com/press/#badges) for your convenience, or

> You may create your own link, which should read “This site is powered by Netlify”, and include a link back to our home page.

> Must not be a commercial project, whether created by a company or an individual. This prohibition includes commercial support and hosting services.

**Comment by pmario** [comment]
I did see Netlify as a hosting compaty

CI/CD alternatives **may** be 

- https://www.jenkins.io/
- https://circleci.com

but I did not find their Open Source policies yet.

**Comment by pmario** [comment]
May be GitHub itself does allow us to have temporary previews. -- Not sure

**Comment by pmario** [comment]
It seems that's still "alpha" :(  

- https://github.com/actions/deploy-pages/issues/337
- https://github.com/actions/deploy-pages?tab=readme-ov-file#inputs-

**Comment by Jermolene** [comment]
Thanks @pmario – come to think about it, our existing GitHub CI architecture should be able to support building simple previews.

I think all we would need is another GitHub Pages repository wired to https://preview.tiddlywiki.org, and a new GitHub workflow which is triggered on changes to branches that builds the site to `/<branch-name>`, and pushes the changes to the GitHub Pages repo. We'd need some of the work that @saqimtiaz has just done for the CLA so that we can also write a comment to the associated PR with a link to the preview if there isn't one already.

We would lose some useful features such as keeping an environment for each individual deployment (we'd just be maintaining the latest version). We were never going to use a lot of the value added features of platforms like Vercel (comments etc), and wouldn't miss them.

**Comment by pmario** [comment]
I did come to the same conclusion. I always thought Vercel is building much more versions as needed. They triggered the build process immediately. Then I found a typo or two and pushed several version, where every one of them was built. 

So IMO it would be OK, if previews are only built, if we have some "trigger-words" in the commit message. eg: `build-a-preview` or something similar. Just an idea.

**Comment by linonetwo** [comment]
Tiddlywiki's self-contain HTML is convenient here, we can let PR github Action build a HTML, and post the download link to CI artifact as a bot comment.

**Comment by btheado** [comment]
Stackblitz is another alternative. As mentioned on [TW Talk](https://talk.tiddlywiki.org/t/more-on-using-stackblitz-webcontainers-to-run-node-js-tiddlywiki-in-the-browser/5053/3) a long while back, opening the TW repository wasn't working.

Now using this new stackblitz url: https://pr.new/github.com/TiddlyWiki/TiddlyWiki5 it is working fine for me.

And it works to just insert `pr.new` at the front of the pull request url. For example: https://pr.new/github.com/TiddlyWiki/TiddlyWiki5/pull/8443

The `pr.new` url is a redirect to: https://stackblitz.com/~/github.com/TiddlyWiki/TiddlyWiki5/pull/8443

It runs node.js and npm inside the browser. It opens the browser internal nodejs tiddlywiki site in a frame. It even works to edit and save tiddlers using the running tiddlywiki application. The saved tiddler is written back to whatever browser internal filesystem is being used.

**Comment by linonetwo** [comment]
@btheado It is amazing that it auto runs `npm run dev` on open. But it failed to open some tiddler on firefox, did you succeed? If this is working on everyone else, there can be a github action to auto recommend this by commenting like vercel bot.

**Comment by btheado** [comment]
>  But it failed to open some tiddler on firefox, did you succeed? 

I didn't have any problems opening tiddlers in firefox. I did see some flakiness...sometimes I would see a message about git clone failing and sometimes other errors. And it is quite slow to start. But once the tiddlywiki page loads, I haven't seen any issues with it.

**Comment by Jermolene** [comment]
I am delighted to announce that thanks to the generous people at https://netlify.com/ we once again have pull request previews. For example, here's the preview for the [new colour handling improvements PR](https://github.com/TiddlyWiki/TiddlyWiki5/pull/8702#issuecomment-2458996690):

<img width="536" alt="image" src="https://github.com/user-attachments/assets/836e6b1f-2dc6-4702-9c5f-39b694c1fe66">

If you own an outstanding PR you can force the preview to build by pushing new changes to that branch.
