### ISSUE TITLE
[BUG] Geospatial plugin's olc-decode and geopoint operators have reversed latitude and longitude

### ISSUE THREAD

**Issue by btheado** [TiddlyWiki/TiddlyWiki5#8436]
### Describe the bug

The Geometries section of https://en.wikipedia.org/wiki/GeoJSON says 

> Points are [x, y] or [x, y, z]. They may be [[longitude, latitude]](https://en.wikipedia.org/wiki/Geographic_coordinate_system) or [[eastings, northings]](https://en.wikipedia.org/wiki/Eastings_and_northings). Elevation, in meters,[[6]](https://en.wikipedia.org/wiki/GeoJSON#cite_note-6) is an optional third number. They are decimal numbers.

The [olc-decode](https://tiddlywiki.com/prerelease/plugins/tiddlywiki/geospatial/#%24%3A%2Fplugins%2Ftiddlywiki%2Fgeospatial%2Fdocs%2Folc-decode) test is passing because the latitude and longitude is reversed in the expected results. Oxford is located at lat=51.7519375, long=-1.257765625, but the returned geojson is

```js
{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[51.7519375,-1.257765625]}})
```

According to the above wikipedia quote, the longitude should come first and the latitude second.

The [geopoint](https://tiddlywiki.com/prerelease/plugins/tiddlywiki/geospatial/#%24%3A%2Fplugins%2Ftiddlywiki%2Fgeospatial%2Fdocs%2Fgeopoint) expected results are similarly reversed

FYI, the turfjs docs at https://turfjs.org/docs/api/point, say

> coordinates	Array<number>	longitude, latitude position (each in decimal degrees)

### Expected behavior

The geojson output of `olc-decode` and `geopoint` should have [longitude, latitude]

### To Reproduce

Go to https://tiddlywiki.com/prerelease/plugins/tiddlywiki/geospatial/ and add the following text to a tiddler:

```
<$tiddler tiddler="cities/Oxford">

<$geomap startPosition=bounds>
<$geolayer lat={{!!lat}} long={{!!long}}/>
</$geomap>

<$geomap startPosition=bounds>
<$geolayer json={{{[geopoint{!!lat},{!!long}]}}}/>
</$geomap>

<$geomap startPosition=bounds>
<$geolayer json={{{[olc-decode:point[9C3WQP2R+QVH]]}}}/>
</$geomap>

</$tiddler>
````

The 3 maps should all be the same location, but the first one is oxford and the second two are in the Ocean off the east coast of Africa.

### TiddlyWiki Configuration

Geospatial plugin prerelease site

**Comment by Jermolene** [comment]
Thanks @btheado much appreciated. Would you be interested in working on a PR? Is there anything else that has struck you with the Geospatial plugin.

**Comment by btheado** [comment]
> Would you be interested in working on a PR?

Sure, I can do it. The fix for olc-decode is clear (reverse the output), but `geopoint`, I'm not 100% sure. I assume the fix for it  is to keep the `[lat],[long]` input order and reverse the output order?

This is my first exposure to GeoJSON and place codes. I was really surprised GeoJSON uses `long, lat`. It feels so unnatural to my naive self.

> Is there anything else that has struck you with the Geospatial plugin.

I was playing around with mapping some points for an upcoming vacation. I'm finding the widgets and operators very well thought out and easy to use. Great work!

Place codes are pretty easy to get from google maps, but it uses values like "QP2R+QV Oxford, UK" which don't work with the olc-decode operator. I just go to https://plus.codes/map and paste that value to get the full code "9C3WQP2R+QV" which does work.

I think it will be more convenient to deal with a single plus code field with a single copy/paste vs. separate latitude and longitude fields.

**Comment by btheado** [comment]
> Perhaps the olc-decode operator should ignore anything after the OLC code?

Unfortunately it isn't that simple. When the city is present as a suffix, it means it is a shortened code. IOW, a prefix of the full code is dropped and replaced by the city in the suffix. The city becomes a critical part to reconstructing the coordinates.

It looks like the olc library provides [shorten](https://github.com/google/open-location-code/blob/main/Documentation/Specification/API.md#shorten) and [recovernearest](https://github.com/google/open-location-code/blob/main/Documentation/Specification/API.md#recovernearest) methods (also there is an isFull and isShort method). Those methods take latitude and longitude as input, so it requires being able to convert a city into a latitude and longitude and also the reverse.

**Comment by Jermolene** [comment]
Hi @btheado that's frustrating, copy/pasting from Google Maps seems like a critical use case.
