### ISSUE TITLE
[Bug] test-case-widget does not support embedded action-sendmessages

### ISSUE THREAD

**Issue by pmario** [TiddlyWiki/TiddlyWiki5#8458]
The test-case-widget does not contain action-sendmessages. To reproduce

- Use the following code with a testcase-tiddler
- title: `test-new-tiddler-button`
- tag: `$:/tags/wiki-test-spec`
- type: `text/vnd.tiddlywiki-multiple`

```
title: Narrative

This code tests action-sendmessage with tm-new-tiddler

+
title: Output

<$button>
<$action-sendmessage $message="tm-new-tiddler" />
Create a new tiddler
</$button>
```

- If the button is clicked, it creates a new tiddler in the "parent" wiki. 

## Expected

It should create a new tiddler in the testcase environment. 

## Proposal

We should cover the testcase-template `$:/core/ui/testcases/DefaultTemplate` with a navigator-widget, eg. 

```
<$navigator story={{{ [<qualify $:/StoryList/>] }}} history={{{ [<qualify $:/HistoryList/>] }}}>
```

## Screenshot
![image](https://github.com/user-attachments/assets/4df2df2e-1375-41cd-82e9-1a28a133eb54)

## Temporary Preview

https://wip-toc-rewrite.tiddlyhost.com/#test-new-tiddler-button:test-new-tiddler-button%20Examples%2FTOC%2FSimpleToc%2FparentField

**Comment by Jermolene** [comment]
Hi @pmario I really don't like this idea. The whole point of a testcase wiki is that it is a separate independent wiki. If running actions within a testcase could change the surrounding wiki then we wouldn't be able to make guarantees about side effects of running tests.

**Comment by pmario** [comment]
I think there is a misunderstanding here. The screenshot shows the **current behaviour** of the testcase wiki. **I think that's a bug** and it should be fixed. 

The "New Tiddler" should be created inside the testcase wiki and not outside.

**Comment by Jermolene** [comment]
Ah, apologies and thank you @pmario. In that case we are in agreement: the testcase wiki should be hermetically sealed away from the host wiki.
