### ISSUE TITLE
[BUG] Setting of "Default sidebar tab" does not work

### ISSUE THREAD

**Issue by twMat** [TiddlyWiki/TiddlyWiki5#8479]
### Describe the bug

The [setting for Default sidebar tab](https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FControlPanel%2FSettings%2FDefaultSidebarTab) is set to  "Open" by default.

But this does not seem to work; Saving the wiki with some other tab active and reloading the page simply shows the *saved* tab open. This seems to be the case also after the value has been actively changed into another value!

This is especially a problem for my public wikis where I want to visitor to meet my curated "Open" tab and not the long and arbitrary lists in the other tabs.

### Expected behavior

I was expecting that when the wiki is loaded, it has the tab active that is set in the setting, regardless of what tab the wiki had active when the wiki was saved.

### TiddlyWiki Configuration

TW 5.3.5

**Comment by Jermolene** [comment]
Hi @twMat the setting for the default sidebar tab is used as a default if there is no state tiddler (which is the situation when TW starts up). If there is a state tiddler then the default value is ignored.

If you want the wiki to ignore the previous state at startup you can either exclude the state tiddlers from the save operation or make a startup action that sets the required state tiddler.

**Comment by twMat** [comment]
@Jermolene , thank you.

Hm, I would be very surprised if the behaviour you describe is what people are expecting from this setting. And as you note, it is then not trivial to set a "default tab as I define it". And the title of the state tiddler is qualified so I don't think it can be trusted to work permanently...

I'm closing this since it is not a bug then, but is there any point in me making a (new) request to change this setting into how I have outlined how I expect it to work (or do you just disagree with this)? Should I make some kind of poll what people do expect first?

Thanks.

**Comment by Jermolene** [comment]
Hi @twMat we can't change the existing handling of this setting, but we could perhaps introduce a new setting "startup sidebar tab".

**Comment by twMat** [comment]
>"startup sidebar tab"

Yes, from a user perspective this makes more sense. And if the current setting needs to stay, then I'd propose that this new setting is presented in the *same* settings "wrapper", i.e in [$:/core/ui/ControlPanel/Settings/DefaultSidebarTab](https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FControlPanel%2FSettings%2FDefaultSidebarTab).
<br>

>we can't change the existing handling of this setting

I interpret that to mean "it must remain *as a user facing setting*".
