### ISSUE TITLE
[BUG] Unproper background for targeted footnote in markdown

### ISSUE THREAD

**Issue by Leilei332** [TiddlyWiki/TiddlyWiki5#8481]
### Describe the bug

The markdown plugin uses `message-background` as the background color of the targeted footnote. It is proper for most of the palettes, but for some palettes it is unproper.

For the Vanilla palette (and Blanca, Blue, DarkPhotos, Muted, Rocker, Twilight, Nord), the color is proper:

![图片](https://github.com/user-attachments/assets/c5f5b522-4352-41ae-a0a3-6b937e425aed)

For the Solarized palettes (and Spartan, Cupertino Dark, Solar Flare), the color is the same as the background color:

![图片](https://github.com/user-attachments/assets/bcc6f501-b08b-4907-90c6-de5ec9fe9c5c)

For the Contrast palettes, the color is the same as the text which made the footnote text invisible:

![图片](https://github.com/user-attachments/assets/be0aeb01-928d-4bc1-83db-6150b93aeb46)

For the rest, the Gruvbox Dark palette uses a dark blue color which is strange, the Desert Sand palette uses a color which is low-contrast.

![图片](https://github.com/user-attachments/assets/833a5923-8518-4f0b-948c-3d35a75b375c)

### Expected behavior

All the palettes uses a appropriate background color which not only different from the tiddler background but also make the text and link visible.

### To Reproduce

Create a markdown tiddler with the following content:

```markdown
Test[^1]

[^1]: Footnote
```

Click the link beside "Test" and watch the background of footnote.

### TiddlyWiki Configuration

Tiddlywiki 5.3.6-prerelease full edition

**Comment by Jermolene** [comment]
Thank you @Leilei332 I fear there might be quite a few bugs like this, fixing them is very much appreciated.

**Comment by Leilei332** [comment]
I think it is better to create a new index (for example `footnote-target-background`) for the background color of the targeted footnote rather than `message-background` which stands for the background color of `tc-message-box`.
