### ISSUE TITLE
[BUG] links.tiddlywiki.com - all "contributor tiddlers" links point to wrong place

### ISSUE THREAD

**Issue by twMat** [TiddlyWiki/TiddlyWiki5#8491]
### Describe the bug

As an example, [here](https://links.tiddlywiki.org/#Contributor%3A%20mat) is my "contributor tiddler" on links.tiddlywiki.com
The link therein is generated by that site (not by me)
But the link in all such "contributor tiddlers" link to the wrong place - Click it to test - i.e they link to the tiddler itself rather than to the external site that it says. I would expect it to link to where it says.

While at it: How often does that site roam the connected wikis? I created two contributions a few days ago but links still does not show them.

### TiddlyWiki Configuration

[not needed]

**Comment by saqimtiaz** [comment]
@twMat this issue would be more appropriate over at https://github.com/TiddlyWiki/TiddlyWikiLinks/issues otherwise it is likely to be forgotten.

I have manually triggered the build process for links, your additions should show up on the next build in an hour or so.

**Comment by twMat** [comment]
@saqimtiaz - thanks, I've now posted there.

Also thanks for the manual trigger - still though; do you know how often it is set to do the fetching?

**Comment by saqimtiaz** [comment]
@twMat Once an hour. However, builds are automatically stopped after 60 days of inactivity in the repository and need to be manually started again.

**Comment by twMat** [comment]
@saqimtiaz - oh, but after such a manual restart, is the 60 day countdown reset to 60 every time someone makes another new contribution available?

**Comment by Jermolene** [comment]
Would it be possible to build a bot that periodically kicks the repo to reset the countdown?
