### ISSUE TITLE
[IDEA] add drag-and-drop handling to the $:/AdvancedSearch Filter "export" button

### ISSUE THREAD

**Issue by ericshulman** [TiddlyWiki/TiddlyWiki5#8497]
Sometimes I want to export/import a bunch of tiddlers from one TiddlyWiki to another, using the $:/AdvancedSearch > Filter tab, but I don't want to download a JSON file and then drag it to the other TiddlyWiki.

Instead, I just want to drag-and-drop all the matching titles into the other TiddlyWiki.

This can be easily done by making a VERY small change in `$:/core/macros/export`:

Change this:
`<$button popup=<<qualify "$:/state/popup/export">> tooltip=<<hint>> aria-label=<<caption>> class=<<tv-config-toolbar-class>> selectedClass="tc-selected">`
to
`<$button popup=<<qualify "$:/state/popup/export">> tooltip=<<hint>> aria-label=<<caption>> class=<<tv-config-toolbar-class>> selectedClass="tc-selected" dragFilter=<<__exportFilter__>>>`

(i.e., adding `dragFilter=<<__exportFilter__>>` to the `$button`.

With this small change, the export button can now be dragged directly onto another TiddlyWiki to initiate an interactive $:/Import of all the matched tiddlers.

I already have this functionality in the "export" button in https://tiddlytools.com/#TiddlyTools%2FSearch%2FFilters, but it would be convenient if this was also a core usability feature enhancement, so that the same drag-and-drop handling is available from ANY TiddlyWiki, without needing to use my custom search.

**Comment by twMat** [comment]
PR! PR! PR! ... c'mon everybody: ***PR! PR! PR!***

**Comment by AnthonyMuscio** [comment]
Did I understand correctly, Erics example, is that one drags and drops the `>` symbol?

I as I wrote here https://talk.tiddlywiki.org/t/astounding-ux-enhancement-and-proposal-from-eric/10371/5?u=tw_tones I have had a solution for this in the past where a more direct export to JSON button is presented, which can be dragged and dropped to another wiki.
* If installing a bundle or plugin is insufficient to use this and we want it in the core, there is more we can do at the same time. 
   * Allow selection of the shortcut export or drag and drop icons (in my implementation) for each relevant export type (config settings to show/hide) each of which can be dragged as well) 
   * Add additional export tryps such as;
     *  Bookmarklets
     * The new compound tiddler format
     * others...

To test it see https://bookmarklets.tiddlyhost.com/ and advanced search > Filter, the first icon is a JSON that can be dragged elsewhere. If clicked it does the equivalent of Export > JSON (with one click)

**Comment by ericshulman** [comment]
> Did I understand correctly, Erics example, is that one drags and drops the `>` symbol?

There is no ">" symbol in the $:/AdvancedSearch Filters tab.  There IS, however, a down-arrow symbol, which you can use to select a previous saved filter... but this is NOT what I was referring to.  Rather, once you've entered (or selected) a filter into the search input, several additional buttons appear.  Among those buttons is an "export" button ("out-box" with upward pointing arrow).  Normally, when you click this button you get a drop-down to select an export format (CSV, JSON, Static HTML, or TID text file).

What I am proposing is to add a `dragFilter=<<__exportFilter__>>` param to that export button, so that if you drag the button instead of clicking it, you can drop it directly on another open TiddlyWiki window to initiate an $:/Import of the entire set of tiddlers that match the filter you have entered.

> I as I wrote here https://talk.tiddlywiki.org/t/astounding-ux-enhancement-and-proposal-from-eric/10371/5?u=tw_tones I have had a solution for this in the past where a more direct export to JSON button is presented, which can be dragged and dropped to another wiki.

My proposal does not add an extra button; it just adds extra functionality to the existing "export" button.

> * If installing a bundle or plugin is insufficient to use this and we want it in the core, there is more we can do at the same time.

If you want to propose other enhancements, you should create a separate ticket, since those changes would be independent of my very minor proposed change to the existing "export" button, and should be discussed and considered separately.

**Comment by AnthonyMuscio** [comment]
This is what I saw, when I made the change, possibly in error;
![Snag_450547f](https://github.com/user-attachments/assets/4683f935-c5c8-431d-9bae-55d4226141b0)

Now corrected, its the Export Icon that is the one we can drag and drop.

I support this idea as it is inconspicuous and useful but perhaps the tooltip message could also change?

However I think further improvements could come along soon as mentioned in the talk thread

**Comment by pmario** [comment]
>PR! PR! PR! ... c'mon everybody: PR! PR! PR!

It's nice to be enthusiastic -- but --

It's not that simple. ... [The current code](https://github.com/TiddlyWiki/TiddlyWiki5/blob/master/core/wiki/macros/export.tid) is  only readable by advanced users and changing it is [error-prone as we can see](https://github.com/TiddlyWiki/TiddlyWiki5/issues/8497#issuecomment-2277057015).

1. So the first step needs to be to make the code human readable
2. Convert `\define` into `\procedure` 
3. Make sure that "old style" text substitution converted to "new style" in a backwards compatible way
4. change `$vars` to `$let`
5. Make sure everything works as before

So what seems to be a 1 minute change turns out to be "some real work"

**And It needs to be documented**. Otherwise it will be an ultra well hidden functionality. 

It turns out that there is not too much info about [How to export tiddlers](https://tiddlywiki.com/#How%20to%20export%20tiddlers). 
There is no info about the $:/AdvancedSearch UI at all. IMO at least the "Filter tab" could need some more general info.

**Comment by pmario** [comment]
@Jermolene -- Do you think it should be implemented as suggested in the OP? 

I personally support the proposal, with the addition, to implement and document it properly with "new style code" as described in my comment.

**Comment by AnthonyMuscio** [comment]
If the tooltip indicated "drag and drop on another wiki" or similar, it would be at least finable.

However as illustrated in advanced search filter tab of https://bookmarklets.tiddlyhost.com/ and when there is a list of tiddlers just a little love could improve this quite a bit.

**Comment by ericshulman** [comment]
Although we definitely should update the documentation and use "new style code", those should really be handled as separate tickets.  That way each ticket represents a small isolated incremental change, with less potential for introducing unanticipated problems by combining them into a single task.
