### ISSUE TITLE
[BUG] Better handling for overflowed content

### ISSUE THREAD

**Issue by Leilei332** [TiddlyWiki/TiddlyWiki5#8523]
### Describe the bug

I've encountred several times that the content of the tiddler overflows when viewing tiddlywiki on my mobile phone, which made the content looked strange.

![截图 2024-08-18 21 40 27](https://github.com/user-attachments/assets/1b580312-2798-4945-a57a-cd0d9a0c66d0)

![截图 2024-08-18 21 46 01](https://github.com/user-attachments/assets/3e704552-1196-4cf4-8142-b4341172afb8)

### Expected behavior

The overflowed content are displayed properly.

### TiddlyWiki Configuration

5.3.6-prerelease

### Additional context

I think the overflowed content should have been handled properly. IMO we can make the overflowed content displayed properly by making it scrollable. My solution is to add `overflow-x:auto` to classes including `tc-tiddler-body`, `tc-tab-content`. What do you think?

![截图 2024-08-18 21 50 21](https://github.com/user-attachments/assets/b4b74aaf-9e52-40fd-8f1a-e969690ea06b)

**Comment by pmario** [comment]
On my mobile tiddlywiki.com works just fine. Which mobile do you use? 

Can you replicate your problem at tiddlywiki.com?

**Comment by Jermolene** [comment]
Thanks @Leilei332 I agree that this issue has a significant impact, and is worth experimenting with fixes.

@pmario as the first illustration implies, you can replicate the problem by visiting this link on mobile and selecting the "config" tab: https://tiddlywiki.com/editions/full/#%24%3A%2Fplugins%2Ftiddlywiki%2Fmarkdown

**Comment by pmario** [comment]
I did visit that page, but with FireFox

Re-visiting with Chrome, it seems to be a Chrome problem handling tables. FireFox has some overflow, but it stops at the border of the mobile screen. So I did not recognize it.

**Comment by pmario** [comment]
Screenshot with Firefox on my mobile

![Screenshot_20240819-083241](https://github.com/user-attachments/assets/d6b4b12c-bb59-44ef-b14b-b4161cc882a9)

**Comment by Leilei332** [comment]
>  Screenshot with Firefox on my mobile
> 
> ![Screenshot_20240819-083241](https://github.com/user-attachments/assets/d6b4b12c-bb59-44ef-b14b-b4161cc882a9)
> 

It looks different from mine. I tested on firefox android 129.0.0 (Fennec) and it looks the same as chrome's (The page was manually scaled):

![Screenshot_20240819-143629.jpg](https://github.com/user-attachments/assets/a6a2af92-872d-445e-85a8-f2505830da6e)

On chrome (127.0, Cromite):

![Screenshot_20240819-143859.jpg](https://github.com/user-attachments/assets/f5996df8-1763-4617-ac61-07df240c1b29)

**Comment by pmario** [comment]
Screenshot with Firefox TOC. I could replicate it there

![Screenshot_20240819-083939](https://github.com/user-attachments/assets/607845ad-ac8c-4493-9a85-3cf4024ab05b)
