### ISSUE TITLE
[Bug] The QR-code in the tiddler toolbar is useless most of the time

### ISSUE THREAD

**Issue by pmario** [TiddlyWiki/TiddlyWiki5#8528]
To reproduce: 

1. Open https://tiddlywiki.com/#HelloThere
2. Click the QR-code button
3. Select - "Raw content of this tiddler" -> Error
4. Select - "Rendered content of this tiddler" -> Error
5. Select - URL -> works

**As a new user** I would stop at 3. or 4. and think it's broken. 

**Proposal:** 

- If we know, that the size of a QR code is more than ~4000 bytes ([alphanumeric](https://en.wikipedia.org/wiki/QR_code#Information_capacity)), we should disable the buttons. 
- If the dropdown is shown URL should be the **frist option**
- If only URL works -> Clicking the button should show the QR code and not the dropdown

**Other issue**

- at https://tiddlywiki.com/#Introduction%20to%20filter%20notation the "Raw content of this tiddler" creates this

![image](https://github.com/user-attachments/assets/34174220-0ed7-4371-9d78-d1a22bc5c56e)

**Screenshot**

90% of the time I do get this info. 

![image](https://github.com/user-attachments/assets/7c423ca4-b1c3-46b4-96b9-6305fa01cd1d)

**Comment by Jermolene** [comment]
The QR Code plugin is not intended to be part of the tiddlywiki.com distribution.
