### ISSUE TITLE
[BUG] MWS application/pdf tiddlers can't be renamed.

### ISSUE THREAD

**Issue by MagicJF** [TiddlyWiki/TiddlyWiki5#8541]
### Describe the bug

If you rename them then link to pdf is broken, that is expected.
If you rename them again to the original name the link to pdf remains broken, that might be a bug.

(See attached Gif)

### Screenshots

![pdf_bug](https://github.com/user-attachments/assets/107cf70d-a3ed-458c-aeed-c27da443ff10)

### TiddlyWiki Configuration

Fresh MWS installation

**Comment by MagicJF** [comment]
Edit:

If you mess arround with naming it will eventually break.
![mess_arround_with_naming](https://github.com/user-attachments/assets/ba2648ab-8e54-4069-a6b9-8d1436631bca)

**Comment by Jermolene** [comment]
Thank you @MagicJF – I think this is a duplication of #8446. We are working on a fix in #8455

**Comment by MagicJF** [comment]
Agree is a duplication, didn't know you were working on it already

**Comment by Jermolene** [comment]
No worries @MagicJF bug reports are always welcome, and it's good to get feedback.
