### ISSUE TITLE
[BUG]  Proposal Update to eslint v9.x

### ISSUE THREAD

**Issue by pmario** [TiddlyWiki/TiddlyWiki5#8563]
Installing eslint v7.32.0 as configured in package.json I do get a lot of warnings. 

```
PS E:\git\tiddly\tiddlywiki\TiddlyWiki5> npm i
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @humanwhocodes/config-array@0.5.0: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@1.2.1: Use @eslint/object-schema instead

added 48 packages, removed 22 packages, changed 13 packages, and audited 116 packages in 3s

15 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS E:\git\tiddly\tiddlywiki\TiddlyWiki5> eslint --version
v7.32.0
```

I do get none of them with eslint v9.9.1 which is the actual one. 

## Proposal

We should update do eslint v9.x

**Comment by pmario** [comment]
It is recommended to also update the configuration file format: 

- https://eslint.org/docs/latest/use/configure/migration-guide  and linked documentation

**Comment by Jermolene** [comment]
Thanks @pmario please go ahead and make a PR.

**Comment by Leilei332** [comment]
Note that formatting rules are [deprecated since v8.53.0](https://eslint.org/blog/2023/10/deprecating-formatting-rules/), so we need to install `@stylistic/eslint-plugin-js` as a plugin of eslint.

**Comment by pmario** [comment]
@Leilei332 ... Yea, we better use https://biomejs.dev/ because it is a linter and a pretty printer in 1 package but 35x faster. So we only need to maintain 1 dependency and 1 configuration. I did already test it for some hours. It seems to work well. 

Biome has a VSCode language server, so it is able to directly show problems -- and then the pretty printer can solve them. 

We may need to make some compromises, since not every TW rule can be configured in a way we do use it atm. But that would also have been the case for ESLint.

**Comment by Leilei332** [comment]
It turned out that biome's formatter doesn't support disabling one specific rule, which is different from ESLint.

**Comment by Leilei332** [comment]
It turned out that biome's formatter doesn't support disabling one specific rule, which is different from ESLint.

**Comment by pmario** [comment]
PR has been merged. So close this one
