### ISSUE TITLE
[BUG] Wrong text alignment Firefox Linux

### ISSUE THREAD

**Issue by BurningTreeC** [TiddlyWiki/TiddlyWiki5#8599]
### Describe the bug

There are problems with text alignment on Firefox that come from the style reset, see the screenshots with the wrong alignment and then one with correct alignment (I removed some lines from the style reset)

### Expected behavior

Correct text alignment cross-browser

### To Reproduce

1. Go to https://tiddlywiki.com using a Firefox web browser
2. Open a tiddler for editing
3. Mark the title with your mouse
4. Observe strange alignment

### Screenshots

![Bildschirmfoto vom 2024-09-14 19-23-01](https://github.com/user-attachments/assets/88aed9c6-3b0b-4242-850b-be10dbfe173a)
![Bildschirmfoto vom 2024-09-14 19-22-17](https://github.com/user-attachments/assets/33de688b-56b6-441f-9655-8b5dae46ab84)

### TiddlyWiki Configuration

- Tiddlywiki version 5.3.6-prerelease
- Single-file configuration and NodeJs
- OS: Arch Linux (will soon test on Windows)
- Fonts tested: Cantarell, SF Pro Regular, Inter

### Additional context

I found out that removing the following lines solves this issue (but arises some other issues with line-heights and Button size...)

```
/**
1. Change the font styles in all browsers.
2. Remove the margin in Firefox and Safari.
*/

button,
input,
optgroup,
select,
textarea {
	font-family: inherit; /* 1 */
	font-size: 100%; /* 1 */
	line-height: 1.15; /* 1 */
	margin: 0; /* 2 */
}
```

So, we will probably figure out the correct overrides for Firefox and apply them in the base stylesheet

**Comment by BurningTreeC** [comment]
Ok, what I've found out now with inspecting the CSS on the page is that the font-family is not applied correctly

**Comment by BurningTreeC** [comment]
Ok, now I've found out that the base style sheet tries to override the fonts in the reset style sheet and that causes conflicts

**Comment by BurningTreeC** [comment]
I'm not quite sure at the moment what causes what but I'm investigating

**Comment by BurningTreeC** [comment]
Now I've found out that addin "system-ui" after "-apple-system" in `$:/themes/tiddlywiki/vanilla/settings/fontfamily` solves various font issues

There's also an error in the base stylesheet where it transcludes and "editorfontfamily" tiddler that doesn't exist:

```
font-family: {{$:/themes/tiddlywiki/vanilla/settings/editorfontfamily}};
```

**Comment by pmario** [comment]
I did create this with tiddlywiki.com -- It seems everything is just fine.

![image](https://github.com/user-attachments/assets/d8c5535e-d015-4384-afb5-ad0318957d9f)

**Comment by pmario** [comment]
Ubuntu 24.04 - FF 131.0b5

![image](https://github.com/user-attachments/assets/6761740f-23d9-4d39-adc7-169b723a17ee)

**Comment by BurningTreeC** [comment]
Before applying "system-ui":
![Bildschirmfoto vom 2024-09-14 21-01-59](https://github.com/user-attachments/assets/c4dc3f6e-9fa0-4eb9-a7d8-11c6709fbdb5)

After applying "system-ui":
![Bildschirmfoto vom 2024-09-14 21-02-39](https://github.com/user-attachments/assets/e2ed7981-ec47-4448-9dd0-2e738c3b9e63)

Note that the fonts are all a bit off
I don't use a full-blown distro like Ubuntu so I may not have all the fonts
But it such cases the system UI font should be preferred, what do you think?

**Comment by BurningTreeC** [comment]
Ok well, I could sort things out. It's the "Helvetica" font having an alias on my system that points to a missing font.
I changed the alias and got it working correctly. Thank you for your time @pmario !

**Comment by BurningTreeC** [comment]
Closing this, sorry for the trouble! :smile:
