### ISSUE TITLE
[BUG] Tables in TW 5.3.6-prerelease Strangely Occupy the Whole Width and Distorts Columns

### ISSUE THREAD

**Issue by kookma** [TiddlyWiki/TiddlyWiki5#8617]
### Describe the bug

Table in TW 5.3.6-prerelease occupy the whole with of tiddler. This is even fine, but TW 5.3.6 distorts the columns.

### Expected behavior

The columns shall be correctly aligned!
It is better to not occupy the whole width!

### To Reproduce

1. Create a new tiddler
2. paste the below wikitext table
```
!! Regular Expressions Quick Reference

|''FLAGS'' |<|<|h
| i |ignore case|case insensitive matching|
|   |whole words|match strings of a-z, 0-9 and _|
| g |global|field start=^, field end=$, all matches|
| m |multi-line|line start=^, line end=$, first match|
|   |first match|field start=^, field end=$, first match|
|''MATCH'' |<|<|h
|''Anchors''|<|<|
| ^ |start of scope|see Flags, match is zero length|
| $ |end of scope|see Flags, match is zero length|
| \b |word boundary|anchor to edge of word, zero length|
| \B |not word boundary|anchor inside word, zero length|
|''Character Classes''|<|<|
| [c] |class of characters|any one matches, e.g. [abc123]|
| [^c] |negated class of characters|any one doesn't match, e.g. [^abc123]|
```

### Screenshots

This is generated by TW 5.3.5 at https://tiddlywiki.com/
![image](https://github.com/user-attachments/assets/1a9ffbe4-9ee6-432f-93b1-e79f1eac5d86)

This is generated by TW 5.3.6-pre at https://tiddlywiki.com/prerelease/
![image](https://github.com/user-attachments/assets/3c96beb3-eb58-4a45-a0d9-babbb6efe321)

### TiddlyWiki Configuration

- Edge 128
- Windows 11

**Comment by pmario** [comment]
Do it as follows and it will line up again. Tables have their own layout mechanism, that can not be influenced very well. 

I did use headings like this `!FLAGS`, which fixed the problem and still uses 100% which looks much nicer within a tiddler. 

```
|!''FLAGS'' |<|<|
| i |ignore case|case insensitive matching|
|   |whole words|match strings of a-z, 0-9 and _|
| g |global|field start=^, field end=$, all matches|
| m |multi-line|line start=^, line end=$, first match|
|   |first match|field start=^, field end=$, first match|
|!''MATCH'' |<|<|
|''Anchors''|<|<|
| ^ |start of scope|see Flags, match is zero length|
| $ |end of scope|see Flags, match is zero length|
| \b |word boundary|anchor to edge of word, zero length|
| \B |not word boundary|anchor inside word, zero length|
|''Character Classes''|<|<|
| [c] |class of characters|any one matches, e.g. [abc123]|
| [^c] |negated class of characters|any one doesn't match, e.g. [^abc123]|
```

**Comment by pmario** [comment]
tw-preview

![image](https://github.com/user-attachments/assets/09577a22-6b44-457a-b350-4a16bc073c64)

**Comment by Jermolene** [comment]
Hi @kookma I agree that it is an unacceptable regression for table rendering to change in this way. @Leilei332 perhaps we can make the new behaviour require an opt-in via a core class?

**Comment by kookma** [comment]
> Hi @kookma I agree that it is an unacceptable regression for table rendering to change in this way.

I should mention that, the behavior in preview mode in TW 5.3.6p is the same as TW 5.3.5
but in view mode they render table differently (as described above)

**Comment by Jermolene** [comment]
@Leilei332 I think we should revert #8608 and explore alternative approaches.

**Comment by Leilei332** [comment]
IMO we should revert the fix for table overflow but keep the fix for table of contents macro overflow if we revert it.

**Comment by Jermolene** [comment]
> IMO we should revert the fix for table overflow but keep the fix for table of contents macro overflow if we revert it.


Fixed in #8652 thanks @Leilei332

**Comment by pmario** [comment]
@kookma -- pls check if it can be closed

**Comment by Leilei332** [comment]
This problem hasn't been fixed now. We need to revert #8608.

**Comment by kookma** [comment]
> @kookma -- pls check if it can be closed

Testing on https://tiddlywiki.com/prerelease/ (Prerelease built from branch 'master' at commit e591dfd5903a426bad68aa35959a73387b36bf9b of https://github.com/TiddlyWiki/TiddlyWiki5 at 2024-10-02 12:19:02 UTC) does not work for me! The issue still is there!
