### ISSUE TITLE
[BUG] Readme contains an empty "Stats" image 

### ISSUE THREAD

**Issue by pmario** [TiddlyWiki/TiddlyWiki5#8633]
See at: https://github.com/TiddlyWiki/TiddlyWiki5?tab=readme-ov-file#developer-forums

The image does not contain any valuable data. So it should not be there or updated. 

![image](https://github.com/user-attachments/assets/8c3071ba-6fda-40af-a3d8-59c7e3d4a976)

@linonetwo -- [It seems you did include it](https://github.com/pmario/TiddlyWiki5/blame/af7f19d27eb2871086e1b5ac8497adf5900cae61/editions/tw5.com/tiddlers/about/Developers.tid#L11) 7 months ago. Can we update this one.

IMO If we do need to maintain or watch it constantly, to see if it works, we should remove it

**Comment by linonetwo** [comment]
This is because repo name changed. It will require an one time update from organization owners, like https://github.com/TiddlyWiki/TiddlyWiki5/discussions/7979#discussioncomment-8433230
