### ISSUE TITLE
[IDEA] Allow setting temporary variables

### ISSUE THREAD

**Issue by Leilei332** [TiddlyWiki/TiddlyWiki5#8650]
**Is your feature request related to a problem? Please describe.**

There are some occasions when some value has to be saved but shouldn't be kept. For example, copy to clipboard button in many websites changes its icon to a check mark after clicking it once. After the page is reloaded (or after several minutes) its icon changed back to the clipboard. At present this is not possiblr

**Describe the solution you'd like**
Add an `<$action-setvariable/>` widget which allows setting a private variable temporarily within the tiddler, and destroys after the tiddler is closed.

For example, this will show the message temporarily after the button is clicked, and the message will not be shown after it is closed and opened again.

```
\procedure actions()
<$action-setvariable $name="test" $value="test"/>
\end

<$button actions=<<actions>>>Test</$button>

<%if [<test>match[test]] %>
Variable has been set.
<%endif%>
```

**Comment by Jermolene** [comment]
Hi @Leilei332 I think the original request could be accomplished by using a temporary tiddler in the `$:/temp/` namespace. Such tiddlers are ephemeral: they do not get saved or synced.

Here's an implementation of your example using an explicit temporary tiddler:

```
\procedure actions()
<$action-setfield $tiddler="$:/temp/test" $value="test"/>
\end

<$let test={{$:/temp/test}}>

<$button actions=<<actions>>>Test</$button>

<%if [<test>match[test]] %>
Variable has been set.
<%endif%>

</$let>
```

But I appreciate that what you're really asking for is a way for action strings to be able to set variables that are visible in the outer scope. I don't see a good way to accomplish that. The widget tree is built on the fundamental assumption that widgets may not reach up and interfere with their parents.

Potentially the best way forward might be to devise syntactic sugar to make the above construction more reasonable looking.
