### ISSUE TITLE
[MWS] Manage Roles -- what should it do

### ISSUE THREAD

**Issue by pmario** [TiddlyWiki/TiddlyWiki5#8755]
@webplusai 

![image](https://github.com/user-attachments/assets/298b49d8-1566-4477-9c4f-853220a1937b)

- I am not sure what should happen here?
- I would have expected, we can set up access rights for this role

Is the functionality of this UI still WIP (work in progress), or do I miss something. 

--------

IMO we should have a "tag" in the UI, which shows eg: WIP -- so testers know, that the functionality is not finished yet.

**Comment by webplusai** [comment]
The edit role feature allows the user to modify the name and description of roles. It doesn't really have an effect on the behavior of the app

**Comment by pmario** [comment]
Where do we define, what a role can do?

**Comment by webplusai** [comment]
![image](https://github.com/user-attachments/assets/19906ec3-4ee7-4e5e-aeb9-85d1d4e1c6a6)

It is defined in the ACL configuration for a tiddler. For example, on this page http://127.0.0.1:8080/admin/acl/recipe-rho/bag-beta the admin can configure what permissions users with a certain role has

**Comment by pmario** [comment]
In the screenshot there is the READ description, that says: `Allows the user to create tiddlers` --- Is that a typo? IMO Read permission does not include modification rights.

**Comment by pmario** [comment]
Since every role can be deleted. What happens, if I do delete all roles for a bag?
Is there an owner, which can not be deleted?
Why is it possible to delete ADMIN?

**Comment by webplusai** [comment]
> In the screenshot there is the READ description, that says: `Allows the user to create tiddlers` --- Is that a typo? IMO Read permission does not include modification rights.

Yeah, the READ description was a typo, I'll correct that.

**Comment by webplusai** [comment]
> What are the possible permissions?

Possible permissions are WRITE and READ. These permissions are assigned to specific roles  with respect to a recipe or bag.

**Comment by webplusai** [comment]
> Since every role can be deleted. What happens, if I do delete all roles for a bag? Is there an owner, which can not be deleted? Why is it possible to delete ADMIN?

Not all roles can be deleted. The ADMIN role can not be deleted. Also, if the system has multiple ADMIN users, only N-1 admin accounts can be deleted, this means that there must be at least one ADMIN account at all times.

**Comment by pmario** [comment]
@webplusai -- How can I open the recipe and bag ACL config page? 
From your screenshot at: https://github.com/TiddlyWiki/TiddlyWiki5/issues/8755#issuecomment-2487811583

**Comment by Jermolene** [comment]
Thanks @pmario @webplusai – it would be very helpful to develop some documentation updates from this discussion.

**Comment by pmario** [comment]
Close this one, since UI has changed in a OK way.
