### ISSUE TITLE
[MWS] MultiWikiClient -- Strange long tiddler title

### ISSUE THREAD

**Issue by pmario** [TiddlyWiki/TiddlyWiki5#8758]
When I have a look at the MultiWikiClient plugin I see this tiddler title: `$:/config/Server/ExternalFilters/[all[tiddlers]] -[[$:/isEncrypted]] -[prefix[$:/temp/]] -[prefix[$:/status/]] -[[$:/boot/boot.js]] -[[$:/boot/bootprefix.js]] -[[$:/library/sjcl.js]] -[[$:/core]]`

@jermolene

- Is this an intentional tiddler title?
- If yes -- why?

![image](https://github.com/user-attachments/assets/dfb86d02-d3a9-4779-b84b-b77f0621bac6)

**Comment by Jermolene** [comment]
Hi @pmario yes, it's the same mechanism as we already use in the client server edition:

<img width="1354" alt="image" src="https://github.com/user-attachments/assets/fc25e9de-f832-4198-9dfb-67ba27a7520d">
