### ISSUE TITLE
[MWS] Add New User -- Passwords do not match -- User created successfully - both texts are visible

### ISSUE THREAD

**Issue by pmario** [TiddlyWiki/TiddlyWiki5#8773]
Add New User -- Passwords do not match -- User created successfully - both texts are visible

**To reproduce**

- I did create an issue with 2 **not** matching PWs -> So "Passwords do not match" text is shown
- I did create a new user with matching PWs -> User created successfully is shown

**Expected**

- "Passwords do not match" should go away

![image](https://github.com/user-attachments/assets/ebd39bc1-1d8f-4a96-9bbf-a2958144b6d8)

**Comment by webplusai** [comment]
My fix in https://github.com/TiddlyWiki/TiddlyWiki5/issues/8774 also fix this issue.

**Comment by pmario** [comment]
Seems to work now. So close
