### ISSUE TITLE
[IDEA] MWS - Admin Menu should have a Overview element as the first menu item

### ISSUE THREAD

**Issue by pmario** [TiddlyWiki/TiddlyWiki5#8777]
As the title says: Admin Menue should have a Overview element as the first menue item

**For Admins**

![image](https://github.com/user-attachments/assets/deae5110-44fd-489b-be8b-198eec9cb42f)

**For Users**

The "Overview" text should be **white**

![image](https://github.com/user-attachments/assets/1538a0c3-2f81-44ff-999d-2a12543939d7)

**Comment by webplusai** [comment]
@pmario @Jermolene 

Do you want to replace the gear icon with the text "Overview"?

**Comment by Jermolene** [comment]
@pmario I am also unclear what you are suggesting. If you mean a new menu item "Overview" that is displayed in the admin menu, or user toolbar, and that the menu item should be a link to the root then I don't agree. It would be more conventional to make it be a home link at the top left.

**Comment by pmario** [comment]
This can be closed now, since the "Admin UI" has a "Home" button now.

![image](https://github.com/user-attachments/assets/a7e0d05b-6519-44d8-b063-41ec7626fab9)
