### ISSUE TITLE
[BUG] Node.js Server: Incorrect redirect after HTTP Basic Auth when using path-prefix

### ISSUE THREAD

**Issue by jrbntt** [TiddlyWiki/TiddlyWiki5#8788]
### Describe the bug

The specific combination of the web server `path-prefix` parameter and `readers=(anon)` results in an incorrect HTTP Redirect after successful authentication via the `/login-basic` route. Instead of redirecting to the URI including the path-prefix, the user is redirected to the root of the web server "/".

### Expected behavior

The handler for basic authentication should redirect to a URI that includes the value of `path-prefix` (if configured).

### To Reproduce

1. Start a Node.js TiddlyWik instance using both `path-prefix` and anonymous read access:
   * `node ./tiddlywiki.js ./editions/server/ --listen username=test password=test readers="(anon)" path-prefix=/test`
2. Navigate to http://127.0.0.1:8080/test/
   * Verify that the anonymous access allows reading
3. Navigate to http://127.0.0.1:8080/test/login-basic and enter the credentials for test user specified in step 1
4. User is redirected to http://127.0.0.1:8080/ instead of http://127.0.0.1:8080/test/

### TiddlyWiki Configuration

- Version: 5.3.7-prerelease
- Saver: Node.js
- Plugins: 
  - tiddlyweb
  - filesystem
- OS: All (tested on Windows)
- Browser: All (tested on Firefox v133.0)

### Additional context

This *only* appears to happen when the anonymous reader access is enabled and the user manually authenticates with "/login-basic". If I change the authentication to `readers=(authenticated)`, then the user is authenticated prior to the wiki loading and there is no invalid redirect.

**Comment by Jermolene** [comment]
Thank you @jrbntt
