### ISSUE TITLE
[BUG] [each[color]] first result tiddler does not have a "color" field

### ISSUE THREAD

**Issue by pmario** [TiddlyWiki/TiddlyWiki5#8797]
It seems there is a bug: `[each[color]]` first result tiddler does not have a "color" field

https://tiddlywiki.com/#%22A%20free%2C%20open%20source%20wiki%20revisited%22%20by%20Mark%20Gibbs%2C%20NetworkWorld

![image](https://github.com/user-attachments/assets/9cd6c608-60af-4d90-8d96-1e3412f452b5)

![image](https://github.com/user-attachments/assets/829fd8c6-0d58-488b-ba7b-af00776b0a3e)

**Comment by btheado** [comment]
The [documentation](https://tiddlywiki.com/#each%20Operator) already describes that as expected behavior:

> Note that if a tiddler does not contain field F, it is treated as if the value of the field were empty. Thus, a filter expression such as [each[motovun]] will return one tiddler that doesn't have a motovun field, as well as one tiddler with each distinct value of that field, if any. To obtain just the tiddlers that have a non-blank value for the motovun field one can use [each[motovun]has[motovun]].

**Comment by pmario** [comment]
I know. But IMO describing a workaround does not make it right.

**Comment by btheado** [comment]
See this [mailing list discussion](https://groups.google.com/g/tiddlywiki/c/8nnE3HH9pr8/m/94ufowMMAgAJ?utm_medium=email&utm_source=footer&pli=1) which led Jeremy to add that documentation.

**Comment by pmario** [comment]
---- rant

Yea. If we want to kill a bugfix, [backwards compatibility](https://groups.google.com/g/tiddlywiki/c/8nnE3HH9pr8/m/KKGAljawCgAJ) is the weapon of choice :/
