### ISSUE TITLE
[IDEA] New tag for mulit wiki server branch

### ISSUE THREAD

**Issue by pmario** [TiddlyWiki/TiddlyWiki5#8809]
@Jermolene -- I think there is a problem: https://github.com/TiddlyWiki/TiddlyWiki5/tags

IMO The mulit-wiki-server branch should not be tagged atm. IMO it will be part of a new version? Or do I miss something.

**Comment by pmario** [comment]
I see. OK - close issue

**Comment by Jermolene** [comment]
Thanks @pmario I would welcome your thoughts on the approach I'm exploring.

**Comment by pmario** [comment]
@Jermolene -- I've had some time to visit this issue again.

I think it is OK 

- to have a https://github.com/TiddlyWiki/MWS repository (MWS repo), 
- which will "populated" by the TW https://github.com/TiddlyWiki/TiddlyWiki5/tree/multi-wiki-support branch (mws branch)
    - The `package.json` file from the branch will be copied over to the repo

The repo could also contain some "test edition" *.sqlite database files, if needed. So *.sqlite files will not "pollute" the single-file repository.

I am not 100 sure, where the mws-docs edition should be located. 

- It could be part of the MWS repo or
- It could also be part of the mws-branch in the main TW5 repository

Just some thoughts for the moment

**Comment by Jermolene** [comment]
Hi @pmario I'm keeping the docs within the multiwikidocs edition in the multi-wiki-support branch of the TW5 repo because I want to keep the MWS repo as small as possible to reflect its very limited purpose.
