### ISSUE TITLE
MWS : Reconfigure Anonymous Access dialogue checkboxes always checked

### ISSUE THREAD

**Issue by Jermolene** [TiddlyWiki/TiddlyWiki5#8818]
When opening the Reconfigure Anonymous Access dialogue after clearing the checkboxes I find that the checkboxes are checked again the next time I open the dialogue.

Steps to reproduce:

1. Start a fresh install of MWS with `npm install` followed by `npm start`
2. Open http://localhost:8080 in a browser
3. Verify that the warning banner about  anonymous is displyed
4. Click the button to create an admin user, and verify that the user is logged in as expected using the menu at the top right
5. Click the menu item "Reconfigure Anonymous Access"
6. A dialogue is displayed with both "allow anonymous reads" and "allow anonymous writes" checked
7. Uncheck both options and click the "save" button
8. Click the menu item "Reconfigure Anonymous Access"
9. Observe that the checkboxes are checked again

<img width="569" alt="image" src="https://github.com/user-attachments/assets/fbaddb05-b3e9-49c0-b8f5-ea658e641a8a" />

cc @webplusai

**Comment by pmario** [comment]
@Jermolene -- I think this issue is not valid anymore. The initial dialogue does contain "unchecked" checkboxes for me. 

For me it seems the checkbox **values** are shown and edited in the right way. 

The behaviour is a different topic

**Comment by Jermolene** [comment]
Thanks @pmario I've verified it too.
