### ISSUE TITLE
MWS Documentation Improvement

### ISSUE THREAD

**Issue by MagicJF** [TiddlyWiki/TiddlyWiki5#8828]
### Describe the bug

Is not clear to me if this is a contradiction or am I missing something
![IMG_0024](https://github.com/user-attachments/assets/452a144f-2e32-4acd-bfa1-b61063701321)
I suggest rephrasing or give more context on this section of the documentation.

### TiddlyWiki Configuration

None

**Comment by Jermolene** [comment]
Thanks @MagicJF I agree that these docs seem confused. @webplusai what was the intention here?
