### ISSUE TITLE
MWS: Manage ACL screen should not be accessed within wikis

### ISSUE THREAD

**Issue by Jermolene** [TiddlyWiki/TiddlyWiki5#8850]
MWS adds a "Manage ACL" button to all wikis that links to a page for setting up ACL records for the topmost bag and recipe of the wiki.

Placing this button has required making modifications to `$:/core/modules/widgets/navigator.js` which is not acceptable since this file is shared with non-MWS builds of TiddlyWiki.

Instead, the Manage ACL screen should be reachable from the home page. It is suggested that we add a right justified toolbar to the wiki cards, and use a padlock icon to link to the Manage ACL screen.

cc @webplusai

**Comment by pmario** [comment]
@Jermolene -- I think this one is fixed already. 

@webplusai -- Please add some text to your PRs eg: `This PR fixes issue #88xx` ... So related issues are closed, when the PRs are merged.
