### ISSUE TITLE
[BUG] TiddlyHost.com giving a 504 Bad Gateway 

### ISSUE THREAD

**Issue by twukitsch** [TiddlyWiki/TiddlyWiki5#8860]
### Describe the bug
Less a bug, more something to be aware of. Sorry if this is the wrong spot for this.

TiddlyHost.com currently showing:
---

502 Bad Gateway
Tiddlyhost is not responding.

Tiddlyhost may be restarting after an update, or it may be temporarily offline for maintenance. Please wait a few moments and try again.

---

Started last night on my home machine around 10:30pm and continues at 8:45am on my work machine. happens on both Chrome and Edge.

### Expected behavior

Self-explanatory.

### To Reproduce

Go to www.tiddlyhost.com

### TiddlyWiki Configuration

N/A

**Comment by pmario** [comment]
Hi Thomas, 
TiddlyHost is not directly maintained by the TW5 project. It is a 3rd party service. 

There is a post at Talk TiddlyWiki already: https://talk.tiddlywiki.org/t/tiddlyhost-com-is-down/11431 -- so "Simon" the owner of TH should be aware of it already.

**Comment by twukitsch** [comment]
Much appreciated. Thanks for the update and for all your work on this project.

**Comment by pmario** [comment]
Can you please close this issue. We will not be able to fix it.
