### ISSUE TITLE
[BUG]  Not Allowed Characters in Tiddler Title - TiddlyWeb Plugin

### ISSUE THREAD

**Issue by kookma** [TiddlyWiki/TiddlyWiki5#8872]
### Describe the bug

See in Tiddlyweb (https://github.com/TiddlyWiki/TiddlyWiki5/blob/master/plugins/tiddlywiki/tiddlyweb/config-tiddlers-filter.tid)

````
title: $:/config/Server/ExternalFilters/[all[tiddlers]] -[[$:/isEncrypted]] -[prefix[$:/temp/]] -[prefix[$:/status/]] -[[$:/boot/boot.js]] -[[$:/boot/bootprefix.js]] -[[$:/library/sjcl.js]] -[[$:/core]]
````

Isn't it a TW syntax rule to not use `[..]` in the tiddler title?

### Expected behavior

Use title like `title: $:/config/Server/ExternalFilters`

### TiddlyWiki Configuration

TiddlyWiki 5.3.6

**Comment by kookma** [comment]
In my Node.JS development environment it looks like:
![image](https://github.com/user-attachments/assets/614e2e1e-f132-485a-9400-d3452146dcd1)

Ugly and incorrect as per TW syntax rules.

**Comment by Jermolene** [comment]
Hi @kookma it is not incorrect to use double square brackets within a tiddler title, it is just recommended to avoid doing so if you need to refer to that title within a link or filter. That is not the case for a configuration tiddler of this kind. I agree that it is somewhat ugly if one does encounter one of these tiddlers.

**Comment by kookma** [comment]
Is not there any better solution like below?

```
title:  title: $:/config/Server/ExternalFilters
filter: [all[tiddlers]] -[[$:/isEncrypted]] -[prefix[$:/temp/]] -[prefix[$:/status/]] -[[$:/boot/boot.js]] -[[$:/boot/bootprefix.js]] -[[$:/library/sjcl.js]] -[[$:/core]]
text: yes
```

**Comment by Jermolene** [comment]
Hi @kookma the advantage of the current approach is that we can check a particular filter with a single lookup into the tiddler store, going straight for the title of the configuration tiddler. Using the `filter` field means having to search through all tiddlers in the store looking for one with the relevant value. It is also necessary to tolerate duplicate results, whereas the current approach cannot generate duplicate results.

**Comment by kookma** [comment]
Thank you for clarification.
